version: "3.9"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.1.4
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.lbswarm=false
        - traefik.swarm.network=docker2docker
        - traefik.http.routers.elasticsearch.entrypoints=web,websecure
        - traefik.http.routers.elasticsearch.rule=Host(`elasticsearch.docker.local`)
        - traefik.http.services.elasticsearch.loadbalancer.server.port=9200
        - traefik.consulcatalog.connect=true
        - sablier.enable=true
        - sablier.group=devsecops
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 10s
      endpoint_mode: vip
      resources:
        limits:
          memory: 4G
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      SERVICE_NAME: "elasticsearch"
      SERVICE_TAGS: "elastic,search,logs"
    volumes:
      - ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:rw
    # ports:
    #   - "9200:9200"
    networks:
      - docker2docker

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.4
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.lbswarm=false
        - traefik.swarm.network=docker2docker
        - traefik.http.routers.kibana.entrypoints=web,websecure
        - traefik.http.routers.kibana.rule=Host(`kibana.docker.local`)
        - traefik.http.services.kibana.loadbalancer.server.port=5601
        - traefik.consulcatalog.connect=true
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 10s
      endpoint_mode: vip
      resources:
        limits:
          memory: 2G
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      SERVICE_NAME: kibana
      SERVICE_TAGS: dashboard,visualization,logs
      SERVER_NAME: kibana.docker.local
    volumes:
      - ./configs/kibana.yml:/usr/share/kibana/kibana.yml:rw
    # ports:
    #   - "5601:5601"
    networks:
      - docker2docker

  filebeat:
    image: docker.elastic.co/beats/filebeat:9.1.4
    deploy:
      labels:
        - traefik.enable=false
        - traefik.consulcatalog.connect=true
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 10s
      endpoint_mode: vip
      resources:
        limits:
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    user: root
    environment:
      SERVICE_NAME: filebeat
      SERVICE_TAGS: logs,shipper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/filebeat.yml:/usr/share/filebeat/filebeat.yml:rw
    # ports:
    #   - 5066:5066
    networks:
      - docker2docker

  logstash:
    image: docker.elastic.co/logstash/logstash:9.1.4
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.lbswarm=false
        - traefik.swarm.network=docker2docker
        - traefik.http.routers.logstash.entrypoints=web,websecure
        - traefik.http.routers.logstash.rule=Host(`logstash.docker.local`)
        - traefik.http.services.logstash.loadbalancer.server.port=5400
        - traefik.consulcatalog.connect=true
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 10s
      endpoint_mode: vip
      resources:
        limits:
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      SERVICE_NAME: logstash
      SERVICE_TAGS: logs,processor
    # ports:
    #   - 5400:5400
    #   - 12201:12201
    volumes:
      - ./configs/logstash.conf:/opt/logstash.conf:rw
    networks:
      - docker2docker

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:9.1.4
    deploy:
      labels:
        - traefik.enable=false
        - traefik.consulcatalog.connect=true
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 10s
      endpoint_mode: vip
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    user: root
    environment:
      SERVICE_NAME: metricbeat
      SERVICE_TAGS: metrics,monitoring
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
      - ./configs/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:rw
    # ports:
    #   - 5067:5067
    networks:
      - docker2docker

networks:
  docker2docker:
    external: true
