version: "3.9"

services:

  n8n:
    image: n8nio/n8n:latest
    labels:
      - sablier.enable=true
      - sablier.group=ai
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.lbswarm=false
        - traefik.swarm.network=docker2docker
        - traefik.http.routers.n8n.entrypoints=web,websecure
        - traefik.http.routers.n8n.rule=Host(`n8n.docker.local`)
        - traefik.http.services.n8n.loadbalancer.server.port=5678
        - traefik.consulcatalog.connect=true
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 2G
          cpus: "1.0"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      SERVICE_NAME: n8n
      SERVICE_TAGS: automation,workflow,integration
      N8N_HOST: n8n.docker.local
      N8N_PORT: 5678
      N8N_PROTOCOL: http
      WEBHOOK_URL: "http://n8n.docker.local"
      GENERIC_TIMEZONE: "Europe/Lisbon"
      DB_TYPE: "postgresdb"
      DB_POSTGRESDB_HOST: "db_postgres"
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: "n8n"
      DB_POSTGRESDB_USER: "root"
      DB_POSTGRESDB_PASSWORD: "${DOCKER_SECRET_DB}"
      N8N_RUNNERS_ENABLED: "true"
      N8N_SECURE_COOKIE: "false"
    volumes:
      - n8n_data:/home/node/.n8n
    # Uncomment the following lines to expose n8n ports
    # Note: Exposing ports is not recommended in production environments.
    # ports:
    #   - "5678:5678"
    networks:
      - docker2docker

networks:
  docker2docker:
    external: true

volumes:
  n8n_data:
    driver: local
