version: '3.9'

services:

# Linked Admin
  linkerd:
    image: buoyantio/linkerd:nightly
    labels:
      - sablier.enable=true
      - sablier.group=mesh
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.lbswarm=false
        - traefik.swarm.network=docker2docker
        - traefik.http.routers.linkerd_mesh.entrypoints=web,websecure
        - traefik.http.routers.linkerd_mesh.rule=Host(`linkerd.docker.local`)
        - traefik.http.services.linkerd_mesh.loadbalancer.server.port=9990
        - traefik.consulcatalog.connect=true
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: "1.0"
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
        SERVICE_NAME: linkerd
        SERVICE_TAGS: mesh, service_mesh, linkerd, linkerd_service
    volumes:
      - ./config/config.yaml:/config.yaml
    # Passing config.yaml file as args to docker
    command: ["/config.yaml"]
    # Uncomment this if you want to expose the Linkerd ports
    # ports:
    #   - 9990:9990
    #   - 8080:8080
    #   - 4140:4140
    networks:
      - docker2docker

networks:
    docker2docker:
        external: true
