version: "3.9"

services:

  bitbucket:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.lbswarm=false
        - traefik.swarm.network=docker2docker
        - traefik.http.routers.bitbucket_ngrok.entrypoints=web,websecure
        - traefik.http.routers.bitbucket_ngrok.rule=Host(`ngrok-bb.docker.local`)
        - traefik.http.services.bitbucket_ngrok.loadbalancer.server.port=4040
        - traefik.consulcatalog.connect=true
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./configs/bitbucket.yaml:/etc/ngrok.yml:rw
    environment:
      - NGROK_AUTHTOKEN=${NGROK_BITBUCKET_AUTHTOKEN}
    networks:
      - docker2docker

  github:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.lbswarm=false
        - traefik.swarm.network=docker2docker
        - traefik.http.routers.github_ngrok.entrypoints=web,websecure
        - traefik.http.routers.github_ngrok.rule=Host(`ngrok-gh.docker.local`)
        - traefik.http.services.github_ngrok.loadbalancer.server.port=4040
        - traefik.consulcatalog.connect=true
      mode: replicated
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command:
      - "start"
      - "--all"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ./configs/github.yaml:/etc/ngrok.yml:rw
    environment:
      - NGROK_AUTHTOKEN=${NGROK_GITHUB_AUTHTOKEN}
    networks:
      - docker2docker

networks:
  docker2docker:
    external: true
