version: "3.9"

services:
  sablier:
    image: sablierapp/sablier:1.11.0
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.lbswarm=false
        - traefik.swarm.network=docker2docker
        - traefik.http.routers.sablier_server.entrypoints=web,websecure
        - traefik.http.routers.sablier_server.rule=Host(`sablier.docker.local`)
        - traefik.http.services.sablier_server.loadbalancer.server.port=10000
        - traefik.consulcatalog.connect=true
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      PROVIDER_NAME: "docker_swarm"
      PROVIDER_DOCKER_STRATEGY: "stop"
      SERVER_PORT: "10000"
      SERVER_BASE_PATH: "/"
      LOGGING_LEVEL: "debug"
      STORAGE_FILE: "/tmp/sablier.json"
      STRATEGY_DYNAMIC_DEFAULT_THEME: "hacker-terminal"
      STRATEGY_DYNAMIC_DEFAULT_REFRESH_FREQUENCY: "5s"
      STRATEGY_BLOCKING_DEFAULT_TIMEOUT: "1m"
      STRATEGY_DYNAMIC_SHOW_DETAILS_BY_DEFAULT: "true"
    # ports:
    #   - '10000:10000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker2docker

networks:
  docker2docker:
    external: true
