version: '3.6'

services:

  adminer:
    image: adminer:standalone
    labels:
      - sablier.enable=true
      - sablier.group=portals
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.lbswarm=false
        - traefik.swarm.network=docker2docker
        - traefik.http.routers.adminer_ui.entrypoints=web,websecure
        - traefik.http.routers.adminer_ui.rule=Host(`adminer.docker.local`)
        - traefik.http.services.adminer_ui.loadbalancer.server.port=8080
        - traefik.consulcatalog.connect=true
        - SERVICE_IGNORE=false
      replicas: 1
      mode: replicated
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
          condition: any
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      SERVICE_NAME: adminer
      SERVICE_TAGS: dbs,admin
    networks:
      - docker2docker

  mongo:
    image: mongo
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.network=docker2docker
        - traefik.swarm.lbswarm=false
        - traefik.http.routers.mongodb.entrypoints=web,websecure
        - traefik.http.routers.mongodb.rule=Host(`mongodb.docker.local`)
        - traefik.http.services.mongodb.loadbalancer.server.port=27017
        - traefik.tcp.routers.mongo.rule=HostSNI(`*`)
        - traefik.tcp.routers.mongo.entrypoints=mongo
        - traefik.tcp.services.mongo.loadbalancer.server.port=28017
        - traefik.consulcatalog.connect=true
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
      resources:
        limits:
            memory: 2G
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      SERVICE_NAME: mongo
      SERVICE_TAG: db, mongodb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DOCKER_SECRET_DB}
    volumes:
      - mongodb_data:/data/db:rw
    # Uncomment this if you want to expose the MongoDB port
    ports:
      - 27017:27017
    networks:
      - docker2docker

  mongo-express:
    image: mongo-express
    labels:
      - sablier.enable=true
      - sablier.group=portals
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.lbswarm=false
        - traefik.swarm.network=docker2docker
        - traefik.http.routers.mongo_express_ui.entrypoints=web,websecure
        - traefik.http.routers.mongo_express_ui.rule=Host(`mongo-express.docker.local`)
        - traefik.http.services.mongo_express_ui.loadbalancer.server.port=8081
        - traefik.consulcatalog.connect=true
      replicas: 1
      mode: replicated
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
          condition: any
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      SERVICE_NAME: mongo-express
      SERVICE_TAGS: dbs,admin,mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DOCKER_SECRET_DB}
      ME_CONFIG_MONGODB_URL: mongodb://root:${DOCKER_SECRET_DB}@db_mongo:27017/
      ME_CONFIG_BASICAUTH: "false"
    networks:
      - docker2docker

  mongo-compass:
    image: mongodb/mongodb-community-server:latest
    labels:
      - sablier.enable=true
      - sablier.group=portals
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.lbswarm=false
        - traefik.swarm.network=docker2docker
        - traefik.http.routers.mongo_compass_ui.entrypoints=web,websecure
        - traefik.http.routers.mongo_compass_ui.rule=Host(`mongo-compass.docker.local`)
        - traefik.http.services.mongo_compass_ui.loadbalancer.server.port=27017
        - traefik.consulcatalog.connect=true
      replicas: 1
      mode: replicated
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
          condition: any
      resources:
        limits:
          cpus: '1.0'
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      SERVICE_NAME: mongo-compass
      SERVICE_TAGS: dbs,admin,mongodb
      MONGODB_INITDB_ROOT_USERNAME: root
      MONGODB_INITDB_ROOT_PASSWORD: ${DOCKER_SECRET_DB}
    networks:
      - docker2docker

  mysql:
    image: mysql:oracle
    deploy:
      labels:
        - traefik.enable=false
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_SECRET_DB}
      MYSQL_ROOT_HOST: '%'
    command: --bind-address=0.0.0.0
    volumes:
      - mysql_data:/var/lib/mysql:rw
    # Uncomment this if you want to expose the MySQL port
    # ports:
    #   - 3306
    networks:
      - docker2docker

  postgres:
    image: postgres:18.1
    deploy:
      labels:
        - traefik.enable=false
      replicas: 1
      update_config:
          parallelism: 1
          delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_HOST_AUTH_METHOD="trust"
      - POSTGRES_PASSWORD=${DOCKER_SECRET_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/18/docker
      # Script to create required databases on start up process
      - ./scripts/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:rw
    # Uncomment this if you want to expose the PostgreSQL port
    # ports:
    #   - 5432
    networks:
      - docker2docker

  clickhouse:
    image: clickhouse/clickhouse-server
    deploy:
      labels:
        - traefik.enable=true
        - traefik.tcp.routers.clickhouse.rule=HostSNI(`*`)
        - traefik.tcp.routers.clickhouse.entrypoints=clickhouse
        - traefik.tcp.services.clickhouse.loadbalancer.server.port=9000
      replicas: 1
      update_config:
          parallelism: 1
          delay: 10s
      restart_policy:
        condition: any
        delay: 5s
        window: 120s
      resources:
        limits:
          memory: 1G
    ulimits:
      nproc: 65536
      nofile:
        soft: 262144
        hard: 262144
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    environment:
      - CLICKHOUSE_DB=devsecops
      - CLICKHOUSE_USER=root
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=${DOCKER_SECRET_DB}
    volumes:
      - clickhouse:/var/lib/clickhouse
    # Uncomment this if you want to expose the ClickHouse port
    # ports:
    #   - 9000:9000
    #   - 8123:8123
    networks:
      - docker2docker


volumes:
  mongodb_data:
    driver: local
  mysql_data:
    driver: local
  postgres_data:
    driver: local
  clickhouse:
    driver: local

networks:
  docker2docker:
    external: true
