services:

  web:
    image: concourse/concourse:8.1.1
    labels:
      - sablier.enable=true
      - sablier.group=cicd
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.lbswarm=false
        - traefik.swarm.network=docker2docker
        - traefik.http.routers.concourse_web.entrypoints=web,websecure
        - traefik.http.routers.concourse_web.rule=Host(`concourse.docker.local`)
        - traefik.http.services.concourse_web.loadbalancer.server.port=8080
        - traefik.consulcatalog.connect=true
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
      resources:
        reservations:
          cpus: '0.50'
          memory: 512M
        limits:
          cpus: '1.00'
          memory: 1G
    environment:
      CONCOURSE_POSTGRES_HOST: db_postgres
      CONCOURSE_POSTGRES_USER: root
      CONCOURSE_POSTGRES_PORT: "5432"
      CONCOURSE_POSTGRES_PASSWORD: ${DOCKER_SECRET_DB}
      CONCOURSE_POSTGRES_DATABASE: concourseci
      CONCOURSE_EXTERNAL_URL: http://concourse.docker.local
      CONCOURSE_CLUSTER_NAME: "Tanus"
      CONCOURSE_LOG_LEVEL: "debug"
      CONCOURSE_ADD_LOCAL_USER: "root:${CONCOURSE_LOCAL_PASSWORD:-admin123@}"
      CONCOURSE_MAIN_TEAM_LOCAL_USER: "root"
      CONCOURSE_MAIN_TEAM_CONFIG: "/opt/concourse/config.yml"
      CONCOURSE_CLIENT_SECRET: ${CONCOURSE_CLIENT_SECRET:-Y29uY291cnNlLXdlYgo=}
      CONCOURSE_TSA_CLIENT_SECRET: ${CONCOURSE_TSA_CLIENT_SECRET:-Y29uY291cnNlLXdvcmtlcgo=}
      CONCOURSE_X_FRAME_OPTIONS: allow
      CONCOURSE_CONTENT_SECURITY_POLICY: "frame-ancestors *;"
      CONCOURSE_TRACING_JAEGER_ENDPOINT: "http://jaeger-all-in-one:14268/api/traces"
    privileged: true
    command: web
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - "./scripts/web:/concourse-keys:rw"
      - "./config/config.yaml:/opt/concourse/config.yml:rw"
    networks:
      - docker2docker

  worker:
    image: concourse/concourse:8.1.1
    user: root
    labels:
      - sablier.enable=true
      - sablier.group=ci
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
      resources:
        reservations:
          cpus: '0.50'
          memory: 512M
        limits:
          cpus: '2.00'
          memory: 2G
    environment:
      CONCOURSE_WORKER_RUNTIME: "containerd"
      CONCOURSE_TSA_HOST: web:2222
      CONCOURSE_TSA_PUBLIC_KEY: "/concourse-keys/tsa_host_key.pub"
      CONCOURSE_TSA_WORKER_PRIVATE_KEY: "/concourse-keys/worker_key"
      CONCOURSE_WORKER_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CLIENT_SECRET: ${CONCOURSE_CLIENT_SECRET:-Y29uY291cnNlLXdlYgo=}
      CONCOURSE_TSA_CLIENT_SECRET: ${CONCOURSE_TSA_CLIENT_SECRET:-Y29uY291cnNlLXdvcmtlcgo=}
      CONCOURSE_BIND_IP: 0.0.0.0
      CONCOURSE_BAGGAGECLAIM_DRIVER: overlay
      CONCOURSE_CONTAINERD_DNS_PROXY_ENABLE: "true"
    privileged: true
    stop_signal: SIGUSR2
    command: worker
    cap_add:
      - ALL
    tmpfs:
      - /run
      - /run/lock
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - "./scripts/worker:/concourse-keys:ro"
    networks:
      - docker2docker

volumes:
  server_data:
    driver: local
  worker_data:
    driver: local

networks:
  docker2docker:
    external: true
