version: "3.9"

services:
  server:
    image: portainer/portainer-ce
    labels:
      - sablier.enable=true
      - sablier.group=portals
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.lbswarm=false
        - traefik.swarm.network=docker2docker
        - traefik.http.routers.server.entrypoints=web,websecure
        - traefik.http.routers.server.rule=Host(`portainer.docker.local`)
        - traefik.http.services.server.loadbalancer.server.port=9000
      replicas: 1
      mode: replicated
      endpoint_mode: vip
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1.0"
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    # ports:
    #   - 9000:9000
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - docker2docker

  agent:
    image: portainer/agent
    labels:
      - sablier.enable=true
      - sablier.group=portals
    deploy:
      labels:
        - "traefik.enable=false"
      replicas: 1
      mode: replicated
      endpoint_mode: vip
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1.0"
          memory: 500M
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    # ports:
    #   - 9001:9001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - docker2docker

volumes:
  portainer_data:
    driver: local

networks:
  docker2docker:
    external: true
