version: "3.9"

services:

  repliqate:
    image: lminlone/repliqate:v0.2.1
    deploy:
      labels:
        - traefik.enable=true
        - traefik.swarm.lbswarm=false
        - traefik.swarm.network=docker2docker
        - traefik.http.routers.replicate.entrypoints=web,websecure
        - traefik.http.routers.replicate.rule=Host(`replicate.docker.local`)
        - traefik.http.services.replicate.loadbalancer.server.port=8080
        - traefik.consulcatalog.connect=true
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: stop-first
      rollback_config:
        parallelism: 1
        delay: 5s
        failure_action: pause
        monitor: 60s
        max_failure_ratio: 0.3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          memory: 4G
          cpus: "2.0"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      SERVICE_NAME: replicate
      SERVICE_TAGS: ai,ml,inference,replicate
    volumes:
      - replicate_data:/data
      - replicate_backups:/backups
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Uncomment the following lines to expose replicate ports
    # Note: Exposing ports is not recommended in production environments.
    # ports:
    #   - "8080:8080"
    networks:
      - docker2docker

networks:
  docker2docker:
    external: true

volumes:
  replicate_data:
    driver: local
  replicate_backups:
    driver: local
